#  ██             ▄                                   ▀██                    ▄    ██          
# ▄▄▄  ▄▄ ▄▄▄   ▄██▄    ▄▄▄▄  ▄▄▄ ▄▄    ▄▄▄ ▄  ▄▄▄▄    ██   ▄▄▄▄     ▄▄▄▄  ▄██▄  ▄▄▄    ▄▄▄▄  
#  ██   ██  ██   ██   ▄█▄▄▄██  ██▀ ▀▀  ██ ██  ▀▀ ▄██   ██  ▀▀ ▄██  ▄█   ▀▀  ██    ██  ▄█   ▀▀ 
#  ██   ██  ██   ██   ██       ██       █▀▀   ▄█▀ ██   ██  ▄█▀ ██  ██       ██    ██  ██      
# ▄██▄ ▄██▄ ██▄  ▀█▄▀  ▀█▄▄▄▀ ▄██▄     ▀████▄ ▀█▄▄▀█▀ ▄██▄ ▀█▄▄▀█▀  ▀█▄▄▄▀  ▀█▄▀ ▄██▄  ▀█▄▄▄▀ 
#                                     ▄█▄▄▄▄▀                                                 
                                                                                            

#
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#


# ▄▀▀ ▄▀▄ █▄ █ █▀ █ ▄▀ 
# ▀▄▄ ▀▄▀ █ ▀█ █▀ █ ▀▄█


general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    gaps_in = 8
    gaps_out = 16
    #gaps_workspaces = 0
    border_size = 6
    col.active_border = rgba(EEB017CC) rgba(CB2211CC) rgba(CB1183CC) 30deg
    col.inactive_border = rgba(2f313cFF)
    layout = master
    allow_tearing = true
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    rounding = 16
    rounding_power = 2
    dim_modal = true
    dim_inactive = true
    dim_strength = 0.15
    dim_special = 0
    dim_around = 0.1
    active_opacity = 0.96
    inactive_opacity = 0.86
    fullscreen_opacity = 1
    blur {
        enabled = true
        size = 2
        passes = 4
        new_optimizations = true
    }
    shadow {
        enabled = false
        range = 8
        render_power = 2
        color = rgba(201C2880)
        color_inactive = rgba(00000000)
    }
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_status = slave
    mfact = 0.58
    special_scale_factor = 0.4
}

input {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    kb_layout = de
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    numlock_by_default = true

    follow_mouse = 1

    touchpad {
		disable_while_typing = true
        natural_scroll = true
		scroll_factor = 0.9
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    disable_hyprland_logo = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    on_focus_under_fullscreen = 2
    enable_anr_dialog = true
    anr_missed_pings = 6
}

ecosystem {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    no_update_news = true
}


# █▄ ▄█ ▄▀▄ █▄ █ █ ▀█▀ ▄▀▄ █▀▄ ▄▀▀
# █ ▀ █ ▀▄▀ █ ▀█ █  █  ▀▄▀ █▀▄ ▄██


source = ~/.config/hypr/conf/monitors.conf


# ▄▀▄ █ █ ▀█▀ ▄▀▄ ▄▀▀ ▀█▀ ▄▀▄ █▀▄ ▀█▀
# █▀█ ▀▄█  █  ▀▄▀ ▄██  █  █▀█ █▀▄  █ 


source = ~/.config/hypr/conf/autostart.conf


# █   █ ▄▀▄ █▀▄ █▄▀ ▄▀▀ █▀▄ ▄▀▄ ▄▀▀ ██▀ █▀▄ █ █ █   ██▀ ▄▀▀
# ▀▄▀▄▀ ▀▄▀ █▀▄ █ █ ▄██ █▀  █▀█ ▀▄▄ █▄▄ █▀▄ ▀▄█ █▄▄ █▄▄ ▄██


source = ~/.config/hypr/conf/workspacerules.conf


# █   █ █ █▄ █ █▀▄ ▄▀▄ █   █ █▀▄ █ █ █   ██▀ ▄▀▀
# ▀▄▀▄▀ █ █ ▀█ █▄▀ ▀▄▀ ▀▄▀▄▀ █▀▄ ▀▄█ █▄▄ █▄▄ ▄██


# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
source = ~/.config/hypr/conf/windowrules.conf


# █▄▀ ██▀ ▀▄▀ ██▄ █ █▄ █ █▀▄ ▄▀▀
# █ █ █▄▄  █  █▄█ █ █ ▀█ █▄▀ ▄██


# See https://wiki.hyprland.org/Configuring/Binds/ for more
source = ~/.config/hypr/conf/keybinds.conf


# ▄▀▄ █▄ █ █ █▄ ▄█ ▄▀▄ ▀█▀ █ ▄▀▄ █▄ █ ▄▀▀
# █▀█ █ ▀█ █ █ ▀ █ █▀█  █  █ ▀▄▀ █ ▀█ ▄██


source = ~/.config/hypr/conf/animations.conf


# ▄▀▄ █ █ ██▀ █▀▄ █▀▄ █ █▀▄ ██▀
# ▀▄▀ ▀▄▀ █▄▄ █▀▄ █▀▄ █ █▄▀ █▄▄


source = ~/.config/hypr/conf/override.conf


# ██▀ █▄ █ █ █ 
# █▄▄ █ ▀█ ▀▄▀


source = ~/.config/hypr/conf/env.conf
