# █▄█ ▀▄▀ █▀▄ █▀▄ █ █▀▄ █   ██▀
# █ █  █  █▀  █▀▄ █ █▄▀ █▄▄ █▄▄


general {
    lock_cmd = hyprlock
    unlock_cmd = 
    before_sleep_cmd = hyprlock
    after_sleep_cmd = 
    ignore_dbus_inhibit = false
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 1800
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprlock && hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 2700
    on-timeout = systemctl suspend
}
